### ISSUE TITLE
Kit doesn't work with v12 of node.js

### ISSUE THREAD

**Issue by chrisadesign** [nhsuk/nhsuk-prototype-kit#145]
# Bug Report

## What is the issue?

I was helping someone setup a new machine and get setup with the prototype kit and they were getting errors, turns our it was the node.js version, downgraded them to the same version I had (v10.x) and all worked fine.

## What steps are required to reproduce the issue?

Install latest version of node.js and try to install node packages and run the toolkit.

## What was the environment where this issue occurred?

MacBook Air, Catalina, Node.js 12.x

## Is there anything else you think would be useful?

Update guidance to make it clear which version currently works. At the moment it says 8+.

**Comment by chrimesdev** [comment]
Hey @chrisadesign I'm on Node v12.16.0 (MacBook + Catalina too) and the prototype kit v3.0.8 runs fine on that. I can double check with others who I think may be on v12. Are you using the latest version of the prototype kit?

**Comment by chrisadesign** [comment]
Ah! No, looks like this prototype has been running for a while, it's way back on v2.0.1.

Bug closed!

**Comment by chrimesdev** [comment]
No worries, any version from 3.0.5 should be compatible with v12 https://github.com/nhsuk/nhsuk-prototype-kit/blob/master/CHANGELOG.md#305---29th-october-2019
