### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by TotallyInformation** [nhsuk/nhsuk-prototype-kit#153]
# Bug Report

## What is the issue?

Should this repo be licensed under the OGL? And have Crown Copywrite? 

That is the recommended license for all public sector development I believe?

I can see that you've chosen an MIT license to match that of jQuery but certainly this wouldn't be acceptable to our organisations in most cases.

**Comment by chrimesdev** [comment]
Hi @TotallyInformation thanks for raising this issue.

The codebase is released under the MIT Licence, which covers both the codebase and any sample code in the documentation. The documentation is Crown copyright and is available under the terms of the Open Government 3.0 licence. The copyright does need updating in the `LICENSE` file for the project.

This licensing follows GOV.UK guidance and is the default for most GOV.UK open source projects ([GOV.UK prototype kit license](https://github.com/alphagov/govuk-prototype-kit/blob/master/LICENCE.txt) & [GOV.UK frontend library license](https://github.com/alphagov/govuk-frontend/blob/master/LICENSE.txt)).

The team will look at updating the copyright and making it clearer the code is MIT and documentation is Crown copyright.

**Comment by TotallyInformation** [comment]
Cool, thanks for looking at it.

**Comment by TotallyInformation** [comment]
Thanks for the clarification Adam & thanks for the repo, very useful.
