### ISSUE TITLE
Enforce stricter password protection within code

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#165]
## Description

An increasing number of prototypes are removing the authentication code, resulting in unauthenticated prototypes being published to the web. There is a risk that members of the public will find these prototypes and think they are real services. This is particularly dangerous at a time when are seeing an increased amount of phishing and scam websites.

A rule of publishing prototypes online is that they must be protected by a username and password:

> Security
> 
> If you publish your prototypes online, they must be protected by a username and password. This is to prevent members of the public finding prototypes and thinking they are real services.
> 
> You must protect user privacy at all times, even when using prototypes. Prototypes made with the kit look like NHS.UK, but do not have the same security provisions. Always make sure you are handling user data appropriately.

We need to look at how we make it more difficult for people to just simply remove the authentication middleware code and how could enforce these policies outside of code.

The username and password is currently set using environment variables (`PROTOTYPE_USERNAME` and `PROTOTYPE_PASSWORD`)

Some things to note ...

- Authentication middleware files can easily be deleted https://github.com/nhsuk/nhsuk-prototype-kit/blob/master/middleware/authentication.js
- Not all hosting providers set default `NODE_ENV` to `production` (Heroku does, Azure doesnt) so the check `env === 'production' || env === 'staging'` may accidentally be being bypassed

**Comment by DomBaker** [comment]
I don't think this is something worth venturing any further with due to the project being open source, any work to try improve the password protection can and will be unpicked, if we make it more difficult to do so it could increase required support.
