### ISSUE TITLE
Review recent user research done on the prototype kit

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#170]
## Description

Before coronavirus we conducted [user research](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Prototype+kit+research) on the NHS.UK prototype kit and came up with a number of findings, this got put on hold due to the pandemic. We should revisit and review these findings and come up with improvements to the prototype kit off the back of them.

**Comment by Indu-Kaila** [comment]
![Uploading Summary - Prototyping Kit past user research and Next Steps.png…]()
