### ISSUE TITLE
Start using GitHub releases feature when doing releases 

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#180]
## Description

Similar to how we release our other GitHub services, start using the GitHub releases functionality when we do a release so that we can keep track releases more easily. This is required for our reporting metrics on deployment frequency.

We may also be able to track prototype kit downloads through the `.zip` file within the release.

**Comment by DomBaker** [comment]
Beginning to look at this with @magicaljellybeans starting by creating the actions for releasing and pull requests 

- [x] release action 
- [x] pull request action 

In doing this removed the dependency on azure DevOps for releasing.
