### ISSUE TITLE
A prototype version of the NHS website

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-prototype-kit#183]
# What
We need to build a prototype version of the NHS website

## Why
There is a growing request among designers to have a prototype version of the NHS website to help simulate journeys from and to the website from other services such as login and the app etc.

## Who
@mcheung-nhs had volunteered to help build this for designers

### Task

- [ ] Gather all web journeys
- [ ] Build journeys based on request

**Comment by Tosin-Balogun** [comment]
@samanthasaw @henocookie @cameronross2 
I have created this issue to catalogue all the request to build the prototype version of the nhsuk frontend. Please add your request in comment below so it helps track what needs building

**Comment by heatherpaxton** [comment]
Homepage with option to have "log in" in the header for simulating users signing in to their NHS login (NHS Account) on NHS.UK

**Comment by samanthasaw** [comment]
NHS uk home page
NHS uk covid hub 

Both with links not working

**Comment by Tosin-Balogun** [comment]
@chrimesdev @mcheung-nhs - This will be merged into the main prototype kit as examples

**Comment by chrimesdev** [comment]
Do prototypes still use the fake Google search landing page to mock a user journey from Google into the NHS website? I wonder if that would be a useful addition, as I know there were a couple floating around and it might save time recreating them.

**Comment by chrimesdev** [comment]
This has been released in V4.5.0
