### ISSUE TITLE
About page in the prototype kit docs links to #standards channel on NHS.UK Slack workspace

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-prototype-kit#185]
# Bug Report

## What is the issue?

The [about page in the NHS.UK prototype kit documentation](https://nhsuk-prototype-kit.azurewebsites.net/docs/about) links to the #standards channel in the NHS.UK Slack workspace which has limited access and hasn't been used for a long time.

I would suggest linking to the [#prototype-kit channel on the NHS service manual Slack](https://nhs-service-manual.slack.com/archives/CFYL2GDGW) workspace.

## What steps are required to reproduce the issue?

1. Visit the [about page in the NHS.UK prototype kit documentation](https://nhsuk-prototype-kit.azurewebsites.net/docs/about)
2. Click either of the "get in touch on the NHS.UK #standards Slack channel" links
3. Taken (if you have access) to the #standards channel in the NHS.UK Slack workspace

## What was the environment where this issue occurred?

* Device: MacBook Pro (15-inch, 2019)
* Operating System: macOS Big Sur Version: 11.4 (20F71)
* Browser: Google Chrome Version: 91.0.4472.114 (Official Build) (x86_64)

**Comment by magicaljellybeans** [comment]
Thanks for the spot @henocookie!
