### ISSUE TITLE
How to override the HTML background colour

### ISSUE THREAD

**Issue by samanthasaw** [nhsuk/nhsuk-prototype-kit#188]
# Issue Report

## What is the issue?

Adding a class to override the HTML background colour did not work. 

## What was the environment where this issue occurred?

* Device: Macbook Pro 15-inch 2017
* Operating System: macOS Big Sur Version 11.4
* Browser: Google Chrome

## Is there anything else you think would be useful in recreating the issue?

I needed to remove the grey HTML background seen here on the NHS App prototype. 
<img width="378" alt="Screenshot 2021-07-15 at 13 21 33" src="https://user-images.githubusercontent.com/38656667/126486755-18d38a2d-ff6a-4c68-858a-a646cecb45d9.png">

I tried the following: 
```
.body {
background-colour: transparent;
}
```

```
.html {
background-colour: transparent;
}
```

```
.html {
background-colour: #F0F4F5;
}
```

I also tried adding important on each of these classes and it didn't work. 

I then realised I needed to change it in views/template.html. 

I added a variable: 
`<html lang="en" style="{{ html_style }}">`

And set this variable on my layout file for the pages I wanted the background colour to change on: 

`{% set html_style = 'background-color: #f0f4f5;' %}
`

**Comment by chrimesdev** [comment]
Hi @samanthasaw the first method you tried wouldn't work because you're using a CSS class selector to target an element. 

For your method to work it would need to have the class name `html` on the element  (`<html class="html">`), instead the CSS would just need to be `html { background-color: #F0F4F5;}` without the `.` to target the `html` element (without a class).

https://www.w3schools.com/cssref/css_selectors.asp

As for your fix, is this something you could open a pull request for?

**Comment by DomBaker** [comment]
It is worth noting we don't directly deal with CSS within the prototype kit, the .css files are pre-compiled versions of the included Sass file. Changing the `html` element background is as straightforward as adding the following to the `main.scss` file `html {
    background-color: pink;
}` 

Here is a visual example of this: 
<img width="539" alt="Screenshot 2021-07-21 at 13 42 25" src="https://user-images.githubusercontent.com/55799839/126491910-e5dab41b-ab06-4d7b-b746-5120d82da908.png">

Any changes made to the CSS file will be superseded by the Sass file as gulp spins up the project which in turn reverts any edited CSS files.

**Comment by magicaljellybeans** [comment]
Just to note the above didn't actually affect a colour change for me but adding this did:
```
body { background-color: pink !important; }
```

**Comment by chrimesdev** [comment]
This would be to do with [specificity in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity), rather than the prototype kit itself.

**Comment by chrimesdev** [comment]
We have released a potential option to get around this in https://github.com/nhsuk/nhsuk-prototype-kit/pull/200 aswell as being able to edit the `main.scss` file as mentioned above.
