### ISSUE TITLE
Add information to REAME for Gitpod

### ISSUE THREAD

**Issue by DomBaker** [nhsuk/nhsuk-prototype-kit#197]
We need to add some information in the README file around Gitpod so that contributors and future contributors understand how the tool works

- [ ] Speak with Content designer around what to add @sarawilcox
- [ ] add content to README

**Comment by chrimesdev** [comment]
I wonder if we could add some documentation to the prototype kit website "Install guide" aswell? https://nhsuk-prototype-kit.azurewebsites.net/docs/install

**Comment by DomBaker** [comment]
Yeah, this sounds like a good idea to me.

**Comment by DomBaker** [comment]
Further expanded in another issue as stated above
