### ISSUE TITLE
Unchecked items not removed from data

### ISSUE THREAD

**Issue by magicaljellybeans** [nhsuk/nhsuk-prototype-kit#198]
# Bug Report

## What is the issue?

Cannot remove unchecked items from "Check your answers" page when unchecking all previously selected items.
It should allow you to remove them all.

## What steps are required to reproduce the issue?

- Go to http://nhsuk-prototype-kit.azurewebsites.net/examples/passing-data/passing-data-check-answers
- Add one or more checked items and save.
- Try changing answers by removing all of the checked items and hitting `Continue`
- Observe that the answers remain the same.
- You can remove them one at a time, but whenever you try to remove all at once, or the last item, you can't.

## What was the environment where this issue occurred?

* Device: Lenovo ThinkPad
* Operating System: Linux
* Browser: Google Chrome

## Is there anything else you think would be useful in recreating the issue?

![ezgif-4-f595d760f1b6](https://user-images.githubusercontent.com/25112739/128885896-241c71f2-1b57-4c82-be9e-0c7a97c0c189.gif)

**Comment by joelanman** [comment]
in case it helps, our code removes unchecked checkboxes:
https://github.com/alphagov/govuk-prototype-kit/pull/340
