### ISSUE TITLE
Add Gitpod install guide to the prototype-kit web app

### ISSUE THREAD

**Issue by DomBaker** [nhsuk/nhsuk-prototype-kit#201]
Adding an installation guide to the prototype kit for Gitpods.

linked #197 

[Working branch](https://github.com/nhsuk/nhsuk-prototype-kit/tree/gitpod-install-guide)

Preposed addition: 
Install page - addition of Gitpod install guide
<img width="659" alt="Screenshot 2021-08-23 at 13 54 07" src="https://user-images.githubusercontent.com/55799839/130450525-84a954e9-44c4-422a-8b63-c684c2750d80.png">
Option 1 numbered steps
<img width="681" alt="Screenshot 2021-08-23 at 13 54 46" src="https://user-images.githubusercontent.com/55799839/130450614-f1e47652-74bd-4443-b669-6bd98b27f7c1.png">
Option 2 paragraphing
<img width="654" alt="Screenshot 2021-08-23 at 13 55 22" src="https://user-images.githubusercontent.com/55799839/130450701-83091bc7-cd5c-43f7-97a5-262921d3678a.png">
Also included on the page is installation information for use within the organisation, again numbered
<img width="675" alt="Screenshot 2021-08-23 at 13 55 49" src="https://user-images.githubusercontent.com/55799839/130450745-13a25f19-4734-4723-8821-9522a713f579.png">
Or paragraphing
<img width="673" alt="Screenshot 2021-08-23 at 13 56 31" src="https://user-images.githubusercontent.com/55799839/130450828-636436da-4e8a-4aff-bdff-6e2a33c53474.png">

Content is still to be to confirmed or improved.

**Comment by DomBaker** [comment]
These are the options I've come up with @nancyhalladay24. Open to ideas though if you feel you have a better one!

**Comment by nancyhalladay24** [comment]
We have noticed that there is a bug on Gitpod when you configure a new repo. Once you select which repo you want to add and click save the Gitpod installer is launched but comes up with an error state to say it has been 'duplicated' or already done. The workspace already has Gitpod installed and so the Gitpod installer should not appear. 
The experience is pretty confusing as it appears as though it has failed when actually Gitpod has been added to the repo. 

Dom is going to report the bug to Gitpod. We need to decide if we want to release the guidance whilst there is a bug or not? 
<img width="591" alt="Screenshot 2021-08-24 at 11 18 24" src="https://user-images.githubusercontent.com/63845568/130766922-d7fe02f1-6785-4269-9638-58803e6cfbb3.png">

**Comment by nancyhalladay24** [comment]
I've had a little look at the option and I think your approach with the numbered list is best. I also identified two options on how we could approach adding this information to the prototype kit guidance [on this mural board](https://app.mural.co/invitation/mural/nhsdigital8118/1629731691383?sender=uc57e8beacae1be0dda5b2638&key=549a11fe-fa56-43be-b9e1-c03abd7a6848). We can either go with a more guided and bespoke experince for NHSUK organisation github users or we can make more generic guidance that applies to everyone. Would be good to set up a meeting tomorrow or some point this week to go over it with you @DomBaker. Once we are happy with it and have decided what to do about the Gitpod bug, it would be good to get @sarawilcox or Pete to check the content for us.

**Comment by nancyhalladay24** [comment]
This has taken a new direction instead of referring to it as Gitpod, we will rebrand it as 'setting up the kit in the browser'. This will be more clear to the user as most people don't know what Gitpod is. We will then introduce Gitpod along the journey. 
The prototype for this work can be found here:
URL: https://service-manual-gitpod.herokuapp.com/docs
UN: gitpod
PW: gitpod

You can also view the mapped out journey on Mural: https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1631105819685/be89d42444c5dc2ab314e2a6973e9e24e0bd36f8?sender=uc57e8beacae1be0dda5b2638

I have requested the team reviews this, then we can see if any iterations are needed. This will also need content design.

**Comment by nancyhalladay24** [comment]
Gitpod handover doc: https://hscic365.sharepoint.com/:w:/s/InternalServiceManual/ERmwyZue9XpKvZr6q32vw0YBksYjiihfLv43_AHbafF8_Q?e=bumxkZ

**Comment by DomBaker** [comment]
Closing as a use case for this is still unknown and has a lowered priority. Can be re-evaluated at a later date.
