### ISSUE TITLE
npm install fails on clean environment

### ISSUE THREAD

**Issue by brainwipe** [nhsuk/nhsuk-prototype-kit#229]
# Bug Report
## What is the issue?

On a clean system, did the following:

```
git clone git@github.com:nhsuk/nhsuk-prototype-kit.git
npm install
```

Error:

```
> nhsuk-prototype-kit@4.8.0 postinstall C:\Projects\nhsuk-prototype-kit
> npm run build


> nhsuk-prototype-kit@4.8.0 build C:\Projects\nhsuk-prototype-kit
> gulp build

'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nhsuk-prototype-kit@4.8.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nhsuk-prototype-kit@4.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rob\AppData\Roaming\npm-cache\_logs\2022-03-31T09_57_54_044Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nhsuk-prototype-kit@4.8.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nhsuk-prototype-kit@4.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rob\AppData\Roaming\npm-cache\_logs\2022-03-31T09_57_54_085Z-debug.log
```
It appears that there's a requirement for `gulp` but that's not included anywhere in the instructions.

Followed both developer and non-developer instructions.

## What was the environment where this issue occurred?

Doesn't matter as I tried it on Win 10, WSL Ubuntu and an npm based docker container.

## Is there anything else you think would be useful in recreating the issue?

Ensure you have clean environment without Gulp installed.

_As an aside..._
Gulp is a technology that's been superseded by [Webpack](https://github.com/webpack).

**Comment by henocookie** [comment]
@wa-rren-dev or @DomBaker are either of you able to look into this?

The only [requirement](https://nhsuk-prototype-kit.azurewebsites.net/docs/install/advanced) listed to install the prototype kit are:

> node.js - LTS version 8 or higher

**Comment by wa-rren-dev** [comment]
Hi @brainwipe, thanks for raising. I'm not able to recreate here - gulp is definitely in the dependencies and shouldn't need any further configuration. I've just tried a fresh VM with Node 16.13.2. What version of Node are you currently using?

![image](https://user-images.githubusercontent.com/6341474/161044333-febb26e5-5b8c-4c37-8256-0ab3329e0790.png)

**Comment by frankieroberto** [comment]
I'm going to close this issue for now, as it’s 2 years old and we’ve not had any further reports of it.

We can re-open it if it looks like it might still be an issue in some environments.
