### ISSUE TITLE
fix readme hyperlink

### ISSUE THREAD

**Issue by renewabristol** [nhsuk/nhsuk-prototype-kit#238]
Following removal of heroku on how-to page, it would make sense to correct the hyperlink which recommends creation of login form during prototyping.

**Comment by renewabristol** [comment]
I can fix this myself, but I don't have push access / can't create branch. 

Suggested fix: README.md:11 
```protected by a <a href="http://nhsuk-prototype-kit.azurewebsites.net/docs/how-tos/">username```

**Comment by roshaanbajwa** [comment]
Fixed in previous release https://github.com/nhsuk/nhsuk-prototype-kit/releases/tag/v4.9.0
