### ISSUE TITLE
Environment variables required for password protecting prototypes online missing from docs

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#251]
The environment variables required for password-protecting prototypes when hosted online are missing from the prototype kit documentation.

The environment variables **need** to be `PROTOTYPE_USERNAME` and `PROTOTYPE_PASSWORD`.

I would expect to find these under the heading "Setting a password" on the [Publish you prototype online page](https://nhsuk-prototype-kit.azurewebsites.net/docs/how-tos/publish-your-prototype-online)

Example of when this has caused confusion: https://nhs-service-manual.slack.com/archives/CFYL2GDGW/p1676282413400739

**Comment by chrimesdev** [comment]
From Stephen Hill on Slack:

> It might also be good to call out that for Railway I believe you need to set a variable called NODE_ENV and set it's value to production. At least thats what I had to do when I was playing around with Railway a few months back.

**Comment by sarawilcox** [comment]
@will-dyson-nhsd tells me it's easy to add the PROTOTYPE_USERNAME & PROTOTYPE_PASSWORD  variables and they are done in the Heroku application dashboard.

I will try to make this change in an upcoming prototype kit release.

**Comment by will-dyson-nhsd** [comment]
Useful references: 
- Heroku: https://devcenter.heroku.com/articles/config-vars#using-the-heroku-dashboard
- Railway: https://docs.railway.app/develop/variables
- NODE_ENV: https://nodejs.dev/en/learn/nodejs-the-difference-between-development-and-production/

**Comment by sarawilcox** [comment]
Hi @chrimesdev, is this what you had in mind? 

![Screenshot 2023-05-04 at 16 36 46](https://user-images.githubusercontent.com/45792959/236454665-f6d5e147-c95f-416b-8905-213700577c7b.png)
