### ISSUE TITLE
Typo in link name

### ISSUE THREAD

**Issue by benchilds** [nhsuk/nhsuk-prototype-kit#283]
# Bug Report

## What is the issue?

The link to the Previous page from https://nhsuk-prototype-kit.azurewebsites.net/docs/install/mac/setup should say "Go to your prototype" but incorrectly says "Got to your protoype".

## What steps are required to reproduce the issue?

Go to https://nhsuk-prototype-kit.azurewebsites.net/docs/install/mac/setup

## What was the environment where this issue occurred?

All devices, all environments, all browsers

## Is there anything else you think would be useful in recreating the issue?

![image](https://github.com/nhsuk/nhsuk-prototype-kit/assets/895189/9791635f-df22-475c-829a-cd6f730e7e4f)

**Comment by frankieroberto** [comment]
@benchilds thanks for reporting this, and sorry it took a while to get fixed!
