### ISSUE TITLE
Session data is lost whenever a template file is saved

### ISSUE THREAD

**Issue by frankieroberto** [nhsuk/nhsuk-prototype-kit#287]
# Bug Report

Currently, whenever you edit a template, the kit restarts itself, which results in any session data being lost.

## What is the issue?

Session data should persist even when the template files are edited.

## What steps are required to reproduce the issue?

Set up a page with a form, and then display the information from the form on the next page using `{{ data | dump }}`.

Then edit a view template, and the page will reload with the data missing.

## What was the environment where this issue occurred?

* Device: Mac
* Browser: Safari

**Comment by edwardhorsford** [comment]
On the GOV.UK prototype kit, I think it only restarts when JS files are changed - not template or assets. I presume something in the NHS kit is watching html files too and restarting - which we could stop.

**Comment by frankieroberto** [comment]
Done a bit of digging into this and my conclusion so far is that the NHS Prototype Kit supports 2 modes for storing data:

* sessionInMemory - this doesn't persist after the server is restarted, which it has to be after every view file is saved, as otherwise the view gets cached
* sessionInCookie - this doesn't seem to work at all for me, for some unknown reason

Digging through the history of the GOV.UK Prototype Kit, it looks like there was a crucial change in this PR, which switched the data to being stored in an ephemeral file, which means it persists even when the server is restarted, and avoids the limitations of cookies: https://github.com/alphagov/govuk-prototype-kit/pull/1658

So possibly the best option would be to copy across those changes?

@joelanman @lfdebrux I know this is going a way back, but does that sound right to you?

**Comment by joelanman** [comment]
sessionInCookie should work, and would persist. The downside is it has a storage limit of 4k, and silently fails if you store more. As you say we implemented file based session storage, first with a library, then wrote our own, I can't remember why. It was this: https://www.npmjs.com/package/session-file-store

**Comment by joelanman** [comment]
Our custom one is here, but I think we updated it since as it had a bug

https://github.com/alphagov/govuk-prototype-kit/pull/2149

**Comment by frankieroberto** [comment]
@joelanman Thanks! I’m not sure yet why the cookie storage option doesn’t seem to be working for me at all with the NHS Prototype Kit.

With the “in memory store”, can you remember if the kit would always rest the server (and lose the in memory session data) whenever a view was edited? Or is that something the NHS Kit has introduced somehow?

Regardless, I suspect that the file storage option is going to be the way to go!

**Comment by joelanman** [comment]
yeh your nodemon watches html, ours doesn't. You may need to add `watch` to nunjucks config, though `nocache` might be enough I'm not sure

https://mozilla.github.io/nunjucks/api.html#configure

**Comment by frankieroberto** [comment]
@joelanman @edwardhorsford thanks! Got an initial fix for this here, I think: #300

(We might still want to move to ephemeral file storage for session data, but that could be a separate issue)
