### ISSUE TITLE
Replace basic authentication with a custom password page

### ISSUE THREAD

**Issue by frankieroberto** [nhsuk/nhsuk-prototype-kit#323]
We (Record a vaccination team) have done some user research with NHS staff on a prototype, and experienced the issue where corporate IT had turned off basic authentication in Windows Edge, and so were unable to access the prototype.

The GOV.UK Prototype Kit team experienced similar, and replaced basic authentication with a custom password screen in this pull request: https://github.com/alphagov/govuk-prototype-kit/issues/1019

We should do similar?

**Comment by joelanman** [comment]
Thats the issue, the PR is here:

- https://github.com/alphagov/govuk-prototype-kit/pull/1182

**Comment by frankieroberto** [comment]
@joelanman ah thanks! Hopefully we can copy a lot of that code.

**Comment by anandamaryon1** [comment]
Thanks for raising this @frankieroberto, this looks like a major blocker for testing designs with internal users, and so a very useful addition to the kit. Are you in a position to be able to implement this, or do we need to find some development help for this?

**Comment by frankieroberto** [comment]
@anandamaryon1 I’ll see how far I can get by copying and pasting the GOVUK implementation.

In the meantime the workaround is to remove the password and also set the environment to “development” mode. (Otherwise it’ll complain of a lack of password)
