### ISSUE TITLE
spring boot  thymeleaf : th:field="*{__${field}__}" creates a hidden field of id="_fieldname" within   <div class="nhsuk-checkboxes__item"  > and this hidden field is required for input submissions to work but this then causes the checkbox to disappear

### ISSUE THREAD

**Issue by vahid-uk** [nhsuk/nhsuk-prototype-kit#353]
# Bug Report
 `<input class="nhsuk-checkboxes__input  th:id="${id}" th:name="${id}"    th:value="*{__${field}__}"       type="checkbox">`
 Above works but when submitting it isn't reading the checkbox 
 
 Typically this should be sufficient for thymleaf to bind an object to  name and id of a given input.
 `<input class="nhsuk-checkboxes__input   th:field="*{__${field}__}"     type="checkbox">`
 
 Being an input this creates `<input type="hidden" id="_fieldName">` where fieldName is the name and prepends the underscore.

 By having an hidden field within the div makes the checkbox disappear and it looks like the JS is controlling this behaviour

 `
   &lt;div class="nhsuk-checkboxes__item"&gt; 
   &lt;input class="nhsuk-checkboxes__input" th:id="${id}" th:name="${id}"
             th:value="*{__${field}__}" type="checkbox"&gt;
&lt;input type="hidden" th:id="_${id}"&gt;
      &lt;label class="nhsuk-label nhsuk-checkboxes__label"  th:for="${id}" th:text="${label}"&gt;
&lt;/div&gt;
 
`    

Can you please allow a hidden field within `<div class="nhsuk-checkboxes__item">`  Since as mentioned it is automatically created by thymleaf when assigning `th:field` to a checkbox and this is essential for the checkbox to be registered with controller action

**Comment by chrimesdev** [comment]
I think this is more an issue with Thymeleaf

**Comment by frankieroberto** [comment]
@vahid-uk Hi! Thanks for reporting this. As @chrimesdev suggested, this seems to be an issue with Thymeleaf rather than the NHS Prototype kit itself?

I’m going to close this issue but please do get back in touch if there’s anything we can help with.
