### ISSUE TITLE
Prototype kit hosting is bringing up 'dangerous' on Chrome

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk-prototype-kit#375]
# Bug Report

## What is the issue?

Site is coming up as dangerous which can be a problem for testing

## What steps are required to reproduce the issue?

Go to https://nhsuk-prototype-kit.azurewebsites.net/templates/check-your-answers 

## What was the environment where this issue occurred?

* Device:
* Operating System:
* Browser:

## Is there anything else you think would be useful in recreating the issue?

<img width="1148" alt="Page showing dangerous" src="https://github.com/user-attachments/assets/fecb42d2-e13a-4b6d-8e01-0c523eac2e60">

**Comment by frankieroberto** [comment]
This is a duplicate of https://github.com/nhsuk/nhsuk.service-manual.prototype-kit.docs/issues/7 which has been closed.
