### ISSUE TITLE
Bug: changing serviceName in config.js does not affect header service name

### ISSUE THREAD

**Issue by anandamaryon1** [nhsuk/nhsuk-prototype-kit#416]
# Bug Report

Not sure where the header is being configured? But I think it should be pulling in serviceName.

I see only this in the template:

```
      {% block header %}
        {{ header({}) }}
      {% endblock %}
```

**Comment by frankieroberto** [comment]
@anandamaryon1 thanks for spotting! Fixed in #417.

Slightly confusingly the pages in the prototype kit inherit from `layout.html` which overrides `template.html` - and it’s the header in `layout.html` which counts.
