### ISSUE TITLE
Decommission old prototype kit website

### ISSUE THREAD

**Issue by anandamaryon1** [nhsuk/nhsuk-prototype-kit#427]
# Bug Report
Remove `https://nhsuk-prototype-kit.azurewebsites.net` and redirect to `https://prototype-kit.service-manual.nhs.uk`

**Comment by frankieroberto** [comment]
(Duplicate of https://github.com/nhsuk/nhsuk.service-manual.prototype-kit.docs/issues/49 )

**Comment by vickytnz** [comment]
Replaced by another ticket
