### ISSUE TITLE
How to guide: Adding custom images and JavaScript - Enhancement

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-prototype-kit#70]
**Images**

Users can add custom image assets by putting image files in the `app/assets/images` folder, then referencing them in HTML with `/images/filename.jpg`. However, the `images` folder does not exist in `assets` and there is no guidance or examples for doing this.

**JavaScript** - Advanced guide?

Users can add custom JavaScript or ES6 modules by writing JavaScript (or using third party libraries) in the `app/assets/javascript` folder then referencing them in HTML in `app/views/includes/scripts.html`. There currently isn't any guidance or examples for doing this.

WIll users be wanting to add custom JavaScript?

**Comment by joelanman** [comment]
In case you didn't know - we recently added guidance to the GOV.UK Prototype Kit:

https://govuk-prototype-kit.herokuapp.com/docs/adding-css-javascript-and-images

**Comment by GrilloPress** [comment]
Would the easiest thing be to have an example in the code as well?

Having helped a few people get set up recently. The places they struggled were when there wasn't an obvious example they could cut and paste in the code itself.

**Comment by davidhunter08** [comment]
@GrilloPress - yeah an example is a good idea and has been added. You can see the work done so far in the commits above your message.

**Comment by chrimesdev** [comment]
Released yesterday in version 1.0.2.
