### ISSUE TITLE
Fix branching examples on Azure

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-prototype-kit#79]
They are currently broken. After clicking on the button https://nhsuk-prototype-kit.azurewebsites.net/examples/branching both options goes to a 404

![image](https://user-images.githubusercontent.com/5756226/53528578-e6752400-3ae1-11e9-9dc6-4a4350bbca46.png)

The code in the routes.js file seems to correct on master on github. 

So maybe an update needs to be pushed to azure?

**Comment by chrimesdev** [comment]
Thanks for raising @GrilloPress I think this is now fixed, if you could confirm on your end. 👨‍💻

**Comment by GrilloPress** [comment]
Looking good to me
