### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-prototype-kit#83]
Been making a prototype for NHS identity

Added their logo and image folder. On Mac so it created the .DS_Store files.

Got picked up by git. Probably worth adding

.DS_Store

To the gitignore file to stop this

**Comment by chrimesdev** [comment]
Had this issue with the NHS digital service manual repository. Will add this to the git ignore along with others, possibly use a template such as https://gist.github.com/andreasonny83/b24e38b7772a3ea362d8e8d238d5a7bc for common things that should be ignored.

**Comment by chrimesdev** [comment]
Fixed in https://github.com/nhsuk/nhsuk-prototype-kit/pull/84 cheers @GrilloPress you the man.
