### ISSUE TITLE
how to swich on my localhost 

### ISSUE THREAD

**Issue by mauroferraresi** [nhsuk/nhsuk-prototype-kit#87]
What to do every time that I switch on my laptop to connect my local host and the heroku app thing

**Comment by bencullimore** [comment]
To run locally - https://nhsuk-prototype-kit.azurewebsites.net/docs/install/mac/run

To publish to heroku - https://nhsuk-prototype-kit.azurewebsites.net/docs/how-tos/heroku

**Comment by mauroferraresi** [comment]
thanks!

**Comment by chrimesdev** [comment]
Closing this issue as we seem to have resolved it.
