### ISSUE TITLE
error on my laptop

### ISSUE THREAD

**Issue by mauroferraresi** [nhsuk/nhsuk-prototype-kit#88]
![error](https://user-images.githubusercontent.com/29603340/54027225-a3c5e280-4198-11e9-93a2-a2c43b94983e.png)

**Comment by chrimesdev** [comment]
Hi @mauroferraresi I believe people have helped you with this outside of this issue.

This isn't a NHS.UK prototype kit specific problem, it seems to be more of a problem with your laptop command line tools installation.

Google would be your best place to go for this kind of thing, you can google the keywords such as "invalid active developer path CommandLineTools". Which gives you many results such as: https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-mojave-update-xcrun-error-invalid-active-devel

Closing this issue as you seem to have fixed it.
