### ISSUE TITLE
Move main.js to below jQuery

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-prototype-kit#98]
Depending on what you're doing with jQuery long term of course...

But helped out Paul Hill today with an issue where he thought the main.js file would work with jQuery.

But the main.js file is included before and therefore he misunderstood and couldn't get his JavaScript to work.

I helped him make a change to the jQuery file in the template so it now works.

I'd suggest that whilst we have jQuery we put main.js to underneath it

**Comment by davidhunter08** [comment]
Thanks, @GrilloPress
